# This is a basic workflow to help you get started with Actions

name: Security-checks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the release-1.0 branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
      - uses: actions/setup-python@v2
      - name: Install truffle
        run:  |
          cd curvefi_adapter
          npm install truffle
      - name: Install Slither
        run: pip3 install slither-analyzer
      - name: Prepare output
        run: |
          mkdir output
      - name: Run analysis
        shell: bash
        run: |
          slither ./curvefi_adapter --filter-paths "openzeppelin|test" --exclude naming-convention >>output/slither_report.txt 2>&1 || true
      - name: Store the report
        uses: actions/upload-artifact@v2
        with:
          name: slither-report
          path: output/slither_report.txt
      - name: Check status
        shell: bash
        run: |
          APPROVED_WARNIGNS=1
          FOUND_WARNINGS=`grep "\d+ result" -Po output/slither_report.txt | sed 's/ result//g'`
          echo "Slither has found $FOUND_WARNINGS"
          if [$FOUND_WARNINGS -gt $APPROVED_WARNIGNS]; then exit(0); fi 
